import { StyleSheet } from "react-native";
import { myColors } from "./colors"; 

export const Styles = StyleSheet.create({
    btnDark: {
        width: 90,
        height: 75,
        borderRadius: 22,
        backgroundColor: myColors.surfaceContainerHigh,
        justifyContent: "center",
        alignItems: "center",
        margin: 6,
        borderWidth: 1,
        borderColor: myColors.outlineVariant,
    },
    smallTextLight: {
        fontSize: 36,
        color: myColors.white,
        fontWeight: "500",
        fontFamily: "System",
    },
    row: {
        maxWidth: '100%',
        flexDirection: "row",
        justifyContent: "center",
        marginVertical: 4,
    },
    viewBottom: {
        flex: 1,
        width: "100%",
        paddingHorizontal: 24,
        paddingTop: 110,
        paddingBottom: 26,
    },
    calculatorContainer: {
        flex: 1,
        flexDirection: "column",
    },
    historyDropdownSection: {
        marginBottom: 16,
    },
    historyDropdownHeader: {
        backgroundColor: myColors.surfaceContainerHigh,
        paddingHorizontal: 20,
        paddingVertical: 16,
        borderRadius: 16,
        borderWidth: 1,
        borderColor: myColors.outlineVariant,
        flexDirection: "row",
        justifyContent: "space-between",
        alignItems: "center",
    },
    historyHeaderText: {
        fontSize: 18,
        color: myColors.white,
        fontWeight: "500",
        fontFamily: "System",
    },
    historyDropdownIcon: {
        fontSize: 16,
        color: myColors.white,
        fontWeight: "600",
    },
    historyPopupOverlay: {
        position: 'absolute',
        top: 0,
        left: 0,
        right: 0,
        bottom: 0,
        zIndex: 1000,
        justifyContent: 'center',
        alignItems: 'center',
    },
    historyPopupBackdrop: {
        position: 'absolute',
        top: 0,
        left: 0,
        right: 0,
        bottom: 0,
        backgroundColor: 'rgba(0, 0, 0, 0.5)',
    },
    historyPopupContent: {
        backgroundColor: myColors.surfaceContainer,
        borderRadius: 16,
        borderWidth: 1,
        borderColor: myColors.outlineVariant,
        width: '85%',
        maxHeight: '60%',
        padding: 16,
    },
    historyPopupHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: 16,
        paddingBottom: 12,
        borderBottomWidth: 1,
        borderBottomColor: myColors.outlineVariant,
    },
    historyPopupTitle: {
        fontSize: 20,
        color: myColors.white,
        fontWeight: '600',
        fontFamily: 'System',
    },
    historyPopupClose: {
        fontSize: 20,
        color: myColors.white,
        fontWeight: '600',
        paddingHorizontal: 8,
        paddingVertical: 4,
    },
    historyPopupScrollView: {
        maxHeight: 300,
    },
    displaySection: {
        justifyContent: "flex-end",
        marginBottom: 12,
    },
    keypadSection: {
        flex: 1,
    },
    screenFirstNumber: {
        fontSize: 100,
        color: myColors.onSurface,
        fontWeight: '300',
        alignSelf: "flex-end",
        fontFamily: "System",
    },
    screenSecondNumber: {
        fontSize: 40,
        color: myColors.onSurfaceVariant,
        fontWeight: '200',
        alignSelf: "flex-end",
        fontFamily: "System",
    },
    historyScrollView: {
        maxHeight: 180,
        padding: 12,
    },
    historyText: {
        fontSize: 18,
        color: myColors.onSurface,
        textAlign: "right",
        marginVertical: 4,
        fontFamily: "System",
        fontWeight: "400",
        paddingVertical: 6,
        paddingHorizontal: 12,
        backgroundColor: myColors.surfaceVariant,
        borderRadius: 10,
        marginBottom: 6,
    },
    historyEmpty: {
        fontSize: 18,
        color: myColors.onSurfaceVariant,
        textAlign: "center",
        fontStyle: "italic",
        marginTop: 24,
        fontFamily: "System",
    },
    resultContainer: {
        width: "100%",
        justifyContent: "center",
        alignSelf: "center",
        marginTop: 6,
        marginBottom: 6,
        backgroundColor: myColors.dark,
        borderRadius: 16,
        padding: 20,
        borderWidth: 1,
        borderColor: myColors.outlineVariant,
    },
    resultText: {
        fontSize: 60,
        color: myColors.white,
        fontWeight: "300",
        textAlign: "right",
        fontFamily: "System",
    },
    titleText: {
        fontSize: 32,
        color: myColors.white,
        fontWeight: "600",
        fontFamily: "System",
        letterSpacing: 0.25,
    },
    toggleButton: {
        backgroundColor: myColors.white,
        paddingHorizontal: 24,
        paddingVertical: 16,
        borderRadius: 20,
        minWidth: 120,
        alignItems: "center",
        borderWidth: 1,
        borderColor: myColors.outlineVariant,
    },
    toggleButtonText: {
        fontSize: 18,
        color: myColors.dark,
        fontWeight: "600",
        fontFamily: "System",
        letterSpacing: 0.1,
    },
    converterContainer: {
        flex: 1,
        width: "100%",
        paddingTop: 120,
        paddingHorizontal: 24,
        backgroundColor: myColors.dark,
    },
    converterScrollContainer: {
        flex: 1,
        backgroundColor: myColors.surfaceContainer,
        borderRadius: 20,
        padding: 24,
        marginBottom: 24,
        borderWidth: 1,
        borderColor: myColors.outlineVariant,
    },
    converterTitle: {
        fontSize: 28,
        color: myColors.white,
        fontWeight: "600",
        fontFamily: "System",
        letterSpacing: 0.25,
    },
    categoryButton: {
        backgroundColor: myColors.surfaceContainerHigh,
        paddingHorizontal: 20,
        paddingVertical: 16,
        borderRadius: 16,
        marginRight: 12,
        minWidth: 100,
        alignItems: "center",
        borderWidth: 1,
        borderColor: myColors.outlineVariant,
    },
    categoryButtonActive: {
        backgroundColor: myColors.white,
        paddingHorizontal: 20,
        paddingVertical: 16,
        borderRadius: 16,
        marginRight: 12,
        minWidth: 100,
        alignItems: "center",
        borderWidth: 1,
        borderColor: myColors.white,
    },
    categoryButtonText: {
        fontSize: 16,
        color: myColors.white,
        fontWeight: "500",
        fontFamily: "System",
    },
    categoryButtonTextActive: {
        fontSize: 16,
        color: myColors.dark,
        fontWeight: "600",
        fontFamily: "System",
    },
    unitButton: {
        backgroundColor: myColors.surfaceContainerHigh,
        paddingHorizontal: 16,
        paddingVertical: 12,
        borderRadius: 12,
        marginRight: 10,
        minWidth: 60,
        alignItems: "center",
        borderWidth: 1,
        borderColor: myColors.outlineVariant,
    },
    unitButtonActive: {
        backgroundColor: myColors.white,
        paddingHorizontal: 16,
        paddingVertical: 12,
        borderRadius: 12,
        marginRight: 10,
        minWidth: 60,
        alignItems: "center",
        borderWidth: 1,
        borderColor: myColors.white,
    },
    unitButtonText: {
        fontSize: 14,
        color: myColors.white,
        fontWeight: "500",
        fontFamily: "System",
    },
    unitButtonTextActive: {
        fontSize: 14,
        color: myColors.dark,
        fontWeight: "600",
        fontFamily: "System",
    },
    converterInput: {
        backgroundColor: myColors.dark,
        color: myColors.white,
        paddingHorizontal: 24,
        paddingVertical: 20,
        borderRadius: 12,
        fontSize: 24,
        textAlign: "center",
        fontFamily: "System",
        fontWeight: "400",
        borderWidth: 1,
        borderColor: myColors.outlineVariant,
    },
    converterResult: {
        backgroundColor: myColors.white,
        paddingHorizontal: 24,
        paddingVertical: 24,
        borderRadius: 16,
        minHeight: 80,
        justifyContent: "center",
        borderWidth: 1,
        borderColor: myColors.white,
    },
    converterResultText: {
        fontSize: 32,
        color: myColors.dark,
        fontWeight: "600",
        textAlign: "center",
        fontFamily: "System",
    },
    converterLabel: {
        fontSize: 18,
        color: myColors.white,
        fontWeight: "500",
        marginBottom: 12,
        fontFamily: "System",
    },
});
